---
title: "Readmission to Hospital Predictor for Diabetic Patients"
bibliography: references.bib
author: "Group29"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

# Summary

This project builds a classification model using logistic regression to analyze various diabetic patient features to predict whether or not the patient will be readmitted to the hospital again or not. 

# Introduction

For this project, we are trying to answer the predictive question: Given a diabetic patient’s demographic, medication history and management of diabetes during hospital stay, can we predict if they will be readmitted to the hospital or not? 

Analysis with machine learning models will identify features more likely to predict patient readmission. This will be important for management of hospital care for diabetic patients, because it will identify areas where changes can be made to decrease patient readmission and reduce burden on the healthcare system.

# Methods

The R programming language [@R] and Python programming language [@Python] were used to perform the analysis. The following R and Python packages were also used to perform the analysis:

* Knitr [@knitr]
* Numpy [@Numpy]
* Pandas [@Pandas]
* Altair [@Altair]
* Hashlib [@Hashlib]
* Matplotlib [@Matplotlib]
* iPython [@iPython]
* Scikit [@Scikit]
* Requests [@Requests]
* Zipfile [@Zipfile]
* Urllib [@Urllib]
* io [@io]
* Warnings [@Warnings]

For statistical analysis (SCRIPT4) specifically:

* StackOverflow [@DSCI571Stack]
* store_vals_function [@DSCI571Var]

The code used to perform the analysis and create this report can be found here: INSERT_URL

## Data

Due to Covid-19, it is critical to reduce the burden on the healthcare system and prevent readmission rates from increasing to make space for Covid cases. Our predictor aims to look at the diabetes management and diagnosis during a patient’s hospital stay to understand how much this affects their readmission. This will allow us to create and improve patient safety protocols to better manage diabetic patients during their hospital stay to provide effective care and prevent readmission during this critical time.  
The data are submitted on behalf of the Center for Clinical and Translational Research, Virginia Commonwealth University, a recipient of NIH CTSA grant UL1 TR00058, and a recipient of the CERNER data. This dataset was collected from 1998-2008 among 130 hospitals and integrated delivery networks throughout the United States of America. 

This data set was sourced from the UCI Machine Learning Repository [@UCI] and can be found [here](https://archive.ics.uci.edu/ml/datasets/diabetes+130-us+hospitals+for+years+1999-2008#). Research from this collected data was used to assess diabetic care during hospitalization and determine if patients were likely to be readmitted or not. The paper by [@paper] can be found [here](https://www.hindawi.com/journals/bmri/2014/781670/). Each row corresponds a unique encounter with a diabetic patient, totaling 74,036,643 unique encounters. Details about each column feature of information collected during these unique encounters can be found [here](https://www.hindawi.com/journals/bmri/2014/781670/tab1/). 

## Analysis

# Results and Discussion

# References
